### ISSUE TITLE
KeyError in compat.py _send_message

### ISSUE THREAD

**Issue by domsj** [openvstorage/pyrakoon#15]
```
Dec 19 03:15:51 NY1SRV0002 python2[39339]: 2017-12-19 03:15:51 75500 -0500 - NY1SRV0002 - 39339/139840258029312 - arakoon_client/pyrakoon - 17834353 - ERROR - 'roLR7yTDk9hMdPGK': Unable to validate master on node
 roLR7yTDk9hMdPGK
Dec 19 03:15:51 NY1SRV0002 python2[39339]: Traceback (most recent call last):
Dec 19 03:15:51 NY1SRV0002 python2[39339]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1185, in determine_master
Dec 19 03:15:51 NY1SRV0002 python2[39339]:     self._validate_master_id(self.master_id):
Dec 19 03:15:51 NY1SRV0002 python2[39339]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1216, in _validate_master_id
Dec 19 03:15:51 NY1SRV0002 python2[39339]:     other_master_id = self._get_master_id_from_node(master_id)
Dec 19 03:15:51 NY1SRV0002 python2[39339]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1207, in _get_master_id_from_node
Dec 19 03:15:51 NY1SRV0002 python2[39339]:     connection = self._send_message(node_id, data)
Dec 19 03:15:51 NY1SRV0002 python2[39339]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1146, in _send_message
Dec 19 03:15:51 NY1SRV0002 python2[39339]:     self._connections.pop(node_id).close()
Dec 19 03:15:51 NY1SRV0002 python2[39339]: KeyError: 'roLR7yTDk9hMdPGK'
```

**Comment by wimpers** [comment]
Was found during scan of the logs. To be investigated what the impact is.

**Comment by wimpers** [comment]
@operations can we check if we still see this error in the logs?

**Comment by jtorreke** [comment]
We no longer see this error message.

```
root@NY1SRV0024:/mnt/monitoring/rsyslog/client_logs# zgrep KeyError NY1SRV*/python2.log*
root@NY1SRV0024:/mnt/monitoring/rsyslog/client_logs#
```

**Comment by wimpers** [comment]
Re-open if needed.
